// Placeholder content for the component gallery only.
import {
  Axe,
  Bone,
  Circle,
  Droplet,
  Feather,
  Flower2,
  Gem,
  Hexagon,
  Leaf,
  ScrollText,
  Shell,
  Sparkles,
  Square,
} from "lucide-react";
import idle from "../assets/sprites/idle.png";
import meditate from "../assets/sprites/meditate.png";
import explore from "../assets/sprites/explore.png";
import contemplate from "../assets/sprites/contemplate.png";
import train from "../assets/sprites/train.png";
import type { ItemData } from "../ui/components";

export const SPRITES = { idle, meditate, explore, contemplate, train };

export const ITEMS: ItemData[] = [
  {
    id: "herb",
    name: "Spirit Herb",
    icon: Leaf,
    rarity: "common",
    category: "Material",
    count: 12,
    description: "A common herb with vitality. Used for basic cultivation.",
    source: "Mountains, Fields",
    use: "Cultivation, Refining",
  },
  {
    id: "wood",
    name: "Ironwood",
    icon: Axe,
    rarity: "common",
    category: "Material",
    count: 6,
    description: "Dense wood that resists rot.",
    source: "Old forests",
    use: "Crafting",
  },
  {
    id: "ore",
    name: "Iron Ore",
    icon: Hexagon,
    rarity: "common",
    category: "Material",
    count: 24,
    description: "Rough ore for basic tools and talismans.",
    source: "Mines",
    use: "Forging",
  },
  {
    id: "crystal",
    name: "Qi Crystal",
    icon: Gem,
    rarity: "rare",
    category: "Material",
    count: 8,
    description: "Condensed qi in crystal form.",
    source: "Spirit veins",
    use: "Cultivation",
  },
  {
    id: "marrow",
    name: "Beast Marrow",
    icon: Bone,
    rarity: "uncommon",
    category: "Material",
    count: 3,
    description: "Rich marrow that strengthens the bones.",
    source: "Spirit beasts",
    use: "Body tempering",
  },
  {
    id: "pill",
    name: "Refining Pill",
    icon: Circle,
    rarity: "uncommon",
    category: "Consumable",
    count: 5,
    description: "Clears a little impurity when taken.",
    source: "Alchemy",
    use: "Impurity",
  },
  {
    id: "talisman",
    name: "Warding Talisman",
    icon: ScrollText,
    rarity: "rare",
    category: "Consumable",
    count: 2,
    description: "Wards off lesser spirits for a night.",
    source: "Sect market",
    use: "Exploration",
  },
  {
    id: "jade",
    name: "Jade Slip",
    icon: Square,
    rarity: "epic",
    category: "Manual",
    count: 1,
    description: "Holds a fragment of an inheritance.",
    source: "Ancient ruins",
    use: "Study",
  },
  {
    id: "lotus",
    name: "Flame Lotus",
    icon: Flower2,
    rarity: "epic",
    category: "Material",
    count: 1,
    description: "A rare fire-aligned material with intense energy.",
    source: "Crimson Fire Valley",
    use: "High-grade Refining",
  },
  {
    id: "core",
    name: "Azure Core",
    icon: Sparkles,
    rarity: "legendary",
    category: "Material",
    count: 1,
    description: "A rare catalyst that stabilises and amplifies cultivation results.",
    source: "Deep sea",
    use: "Breakthroughs",
  },
  {
    id: "feather",
    name: "Phoenix Feather",
    icon: Feather,
    rarity: "mythic",
    category: "Material",
    count: 1,
    description: "Still warm. Said to hold a sliver of rebirth.",
    source: "Unknown",
    use: "Reincarnation",
  },
  {
    id: "shell",
    name: "Tortoise Shell",
    icon: Shell,
    rarity: "uncommon",
    category: "Equipment",
    count: 1,
    description: "A light shield made from an old shell.",
    source: "Rivers",
    use: "Defence",
  },
];

export const CATALYST: ItemData = {
  id: "catalyst",
  name: "Azure Core",
  icon: Droplet,
  rarity: "rare",
  category: "Catalyst",
  count: 3,
  description: "A rare catalyst that stabilises and amplifies cultivation results.",
};
